### ISSUE TITLE
just fyi on docs still needing to reference SNAP LXD

### ISSUE THREAD

**Issue by bmullan** [lxdock/lxdock#159]
Just an fyi but this page doesn't yet reference using SNAP to install LXD.

https://lxdock.readthedocs.io/en/stable/getting_started.html

Saw your announcement on /r/lxd subreddit...!

**Comment by robvdl** [comment]
I'll check it out in the next couple of days, I I thought at some point we had two installation methods documented, but I am not sure if the APT method is even relevant anymore because the PPA repos are long gone.

**Comment by robvdl** [comment]
Since we haven't done a release in like forever, the docs published there are now very old.

The project has been in limbo for a long time, with very little maintenance as I don't actively use it myself anymore, it means we get patches coming in from time to time but no real releases.

I thought we did document installing from snap, it just hasn't made it into a release yet.
