### ISSUE TITLE
lxdock 0.3 release

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#92]
Hi, I am wondering when we can have an lxdock 0.3 release, getting a bit anxious because I need a newer version for my project.

Last time I checked something was holding if up because people were running a newer version of lxd than came with Ubuntu 16.04 LTS or something? is this resolved yet? why is this a concern? To me if it's not an LTS version it shouldn't matter.  Sorry to be a little blunt, but I if people are running non LTS Ubuntu, that is their own problem is it not? and it shouldn't hold up a release right?

**Comment by hsoft** [comment]
@robvdl There's a PR ready: #86. We're waiting on pylxd: https://github.com/lxc/pylxd/pull/234 (and, also, that they have a release themselves). The main problem is that right now, the `master` branch is depending on a direct git repo reference because otherwise, the CI doesn't run. We don't want to make a new release under these conditions.

**Comment by robvdl** [comment]
Ok that's cool.  An interesting thought, what if lxdock were written in Go rather than Python just like lxd itself.  No need to answer this :) it's not likely to happen and that is fine, Python is a great language.  One of the cool things is you can directly use the github.com/lxc/lxd/client library with Go, I have toyed with this before.

**Comment by hsoft** [comment]
Yeah, I agree about Go. Were we to start from scratch again, I would probably seriously consider this option. It would be a good opportunity to learn it. LXDock is a Python program because it started as a *LXC* wrapper, not a LXD one. LXC being written in C and already having builtin python bindings, it was a logical choice to choose python.

**Comment by hsoft** [comment]
Done!
